# Generated by Django 4.2.7 on 2023-11-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='club_member',
            field=models.ManyToManyField(help_text='Select a club member for this competition', to='competition_tracker.clubmember'),
        ),
    ]
